bucket_name = "hotel-reservas-web"
db_username = "admin"
db_password = "*Zyst3was*"
db_name     = "hotel_reservas"
key_name    = "nginx-server.key"
ses_email   = "franklin131@hotmail.com"
vpc_id = "vpc-016efe07a8fa1c51d"